#!/usr/bin/env bash
HOMEWORK=${1?Error: no homework given};

export HOMEWORK=$HOMEWORK
export RESULTS_PATH=results/results.json
export BASE_DIR=tests

cd $HOMEWORK
mkdir results

../compile_local.sh

python3 run_tests.py

cat $RESULTS_PATH

# clean up
#while read question; do
#  rm -rf $question
#done < questions.txt




